version: '3.4'
networks:
  devops-dojo:
volumes:
  # Executar: docker volume create devops-dojo-keycloak-data
  devops-dojo-keycloak-data:
    external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - devops-dojo-keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./backend/people/devops-dojo-realm.json:/tmp/realm.json
    command:
      - -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    networks:
      - devops-dojo
